name       : pep8
version    : 1.7.1
release    : 5
source     :
    - https://github.com/PyCQA/pycodestyle/archive/1.7.1.tar.gz : ac48ac8a27b7d184a698bfc1ba1c441dfeeac359979d71a23a9eebc131d0c6fc
license    : Expat
component  : programming.python
summary    : PEP8 compliance checking
description: |
    PEP8 compliance checking
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
      mv -v "$_f" "${_f}-3"
    done
    %python_install
