name       : pep8
version    : 1.6.2
release    : 3
source     :
    - https://pypi.python.org/packages/source/p/pep8/pep8-1.6.2.tar.gz : b8b7e35630b5539e26a197dfc6005be9e1e9a135496b377723a8ebc01b9bcbff
license    : Expat
summary    : PEP8 compliance checking
description: |
    PEP8 compliance checking
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-setuptools
build      : |
    python2 setup.py build
    python3 setup.py build
install    : |
    python2 setup.py install --root=%installroot% --no-compile -O0
    mv $installdir/usr/bin/pep8 $installdir/usr/bin/pep8-2.7
    python3 setup.py install --root=%installroot% --no-compile -O0
    mv $installdir/usr/bin/pep8 $installdir/usr/bin/pep8-3.5
    ln -sv pep8-2.7 $installdir/usr/bin/pep8
